// GENERATED by scripts/gen_tables.py - DO NOT EDIT BY HAND.
// Reed-Solomon generator polynomial coefficients (GF(256), 0x11D),
// highest degree first, for every distinct parity count in V1-40:
//   [7, 10, 13, 15, 16, 17, 18, 20, 22, 24, 26, 28, 30]
// gen_coeff(parity, i) = coefficient of x^(parity-1-i) of g_p(x).
`ifndef QR_RS_GEN_ROM_VH
`define QR_RS_GEN_ROM_VH

function [7:0] gen_coeff;
    input [4:0] parity;
    input [4:0] idx;
    begin
        case (parity)
            5'd7: gen_coeff = rom7(idx);
            5'd10: gen_coeff = rom10(idx);
            5'd13: gen_coeff = rom13(idx);
            5'd15: gen_coeff = rom15(idx);
            5'd16: gen_coeff = rom16(idx);
            5'd17: gen_coeff = rom17(idx);
            5'd18: gen_coeff = rom18(idx);
            5'd20: gen_coeff = rom20(idx);
            5'd22: gen_coeff = rom22(idx);
            5'd24: gen_coeff = rom24(idx);
            5'd26: gen_coeff = rom26(idx);
            5'd28: gen_coeff = rom28(idx);
            5'd30: gen_coeff = rom30(idx);
            default: gen_coeff = 8'h00;
        endcase
    end
endfunction

function [7:0] rom7;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom7 = 8'h75;
            5'd1: rom7 = 8'h44;
            5'd2: rom7 = 8'h0b;
            5'd3: rom7 = 8'ha4;
            5'd4: rom7 = 8'h9a;
            5'd5: rom7 = 8'h7a;
            5'd6: rom7 = 8'h7f;
            default: rom7 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom10;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom10 = 8'hc1;
            5'd1: rom10 = 8'h9d;
            5'd2: rom10 = 8'h71;
            5'd3: rom10 = 8'h5f;
            5'd4: rom10 = 8'h5e;
            5'd5: rom10 = 8'hc7;
            5'd6: rom10 = 8'h6f;
            5'd7: rom10 = 8'h9f;
            5'd8: rom10 = 8'hc2;
            5'd9: rom10 = 8'hd8;
            default: rom10 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom13;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom13 = 8'h78;
            5'd1: rom13 = 8'h84;
            5'd2: rom13 = 8'h53;
            5'd3: rom13 = 8'h2b;
            5'd4: rom13 = 8'h2e;
            5'd5: rom13 = 8'h0d;
            5'd6: rom13 = 8'h34;
            5'd7: rom13 = 8'h11;
            5'd8: rom13 = 8'hb1;
            5'd9: rom13 = 8'h11;
            5'd10: rom13 = 8'he3;
            5'd11: rom13 = 8'h49;
            5'd12: rom13 = 8'h89;
            default: rom13 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom15;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom15 = 8'h1a;
            5'd1: rom15 = 8'h86;
            5'd2: rom15 = 8'h20;
            5'd3: rom15 = 8'h97;
            5'd4: rom15 = 8'h84;
            5'd5: rom15 = 8'h8b;
            5'd6: rom15 = 8'h69;
            5'd7: rom15 = 8'h69;
            5'd8: rom15 = 8'h0a;
            5'd9: rom15 = 8'h4a;
            5'd10: rom15 = 8'h70;
            5'd11: rom15 = 8'ha3;
            5'd12: rom15 = 8'h6f;
            5'd13: rom15 = 8'hc4;
            5'd14: rom15 = 8'h1d;
            default: rom15 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom16;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom16 = 8'h3b;
            5'd1: rom16 = 8'h24;
            5'd2: rom16 = 8'h32;
            5'd3: rom16 = 8'h62;
            5'd4: rom16 = 8'he5;
            5'd5: rom16 = 8'h29;
            5'd6: rom16 = 8'h41;
            5'd7: rom16 = 8'ha3;
            5'd8: rom16 = 8'h08;
            5'd9: rom16 = 8'h1e;
            5'd10: rom16 = 8'hd1;
            5'd11: rom16 = 8'h44;
            5'd12: rom16 = 8'hbd;
            5'd13: rom16 = 8'h68;
            5'd14: rom16 = 8'h0d;
            5'd15: rom16 = 8'h3b;
            default: rom16 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom17;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom17 = 8'h4f;
            5'd1: rom17 = 8'h63;
            5'd2: rom17 = 8'h7d;
            5'd3: rom17 = 8'h35;
            5'd4: rom17 = 8'h55;
            5'd5: rom17 = 8'h86;
            5'd6: rom17 = 8'h8f;
            5'd7: rom17 = 8'h29;
            5'd8: rom17 = 8'hf9;
            5'd9: rom17 = 8'h53;
            5'd10: rom17 = 8'hc5;
            5'd11: rom17 = 8'h16;
            5'd12: rom17 = 8'h77;
            5'd13: rom17 = 8'h78;
            5'd14: rom17 = 8'h53;
            5'd15: rom17 = 8'h42;
            5'd16: rom17 = 8'h77;
            default: rom17 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom18;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom18 = 8'h92;
            5'd1: rom18 = 8'hd9;
            5'd2: rom18 = 8'h43;
            5'd3: rom18 = 8'h20;
            5'd4: rom18 = 8'h4b;
            5'd5: rom18 = 8'had;
            5'd6: rom18 = 8'h52;
            5'd7: rom18 = 8'h49;
            5'd8: rom18 = 8'hdc;
            5'd9: rom18 = 8'hf0;
            5'd10: rom18 = 8'hd7;
            5'd11: rom18 = 8'hc7;
            5'd12: rom18 = 8'haf;
            5'd13: rom18 = 8'h95;
            5'd14: rom18 = 8'h71;
            5'd15: rom18 = 8'hb7;
            5'd16: rom18 = 8'hfb;
            5'd17: rom18 = 8'hef;
            default: rom18 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom20;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom20 = 8'hae;
            5'd1: rom20 = 8'ha5;
            5'd2: rom20 = 8'h79;
            5'd3: rom20 = 8'h79;
            5'd4: rom20 = 8'hc6;
            5'd5: rom20 = 8'he4;
            5'd6: rom20 = 8'h16;
            5'd7: rom20 = 8'hbb;
            5'd8: rom20 = 8'h24;
            5'd9: rom20 = 8'h45;
            5'd10: rom20 = 8'h96;
            5'd11: rom20 = 8'h70;
            5'd12: rom20 = 8'hdc;
            5'd13: rom20 = 8'h06;
            5'd14: rom20 = 8'h63;
            5'd15: rom20 = 8'h6f;
            5'd16: rom20 = 8'h05;
            5'd17: rom20 = 8'hf0;
            5'd18: rom20 = 8'hb9;
            5'd19: rom20 = 8'h98;
            default: rom20 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom22;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom22 = 8'hf5;
            5'd1: rom22 = 8'h91;
            5'd2: rom22 = 8'h1a;
            5'd3: rom22 = 8'he6;
            5'd4: rom22 = 8'hda;
            5'd5: rom22 = 8'h56;
            5'd6: rom22 = 8'hfd;
            5'd7: rom22 = 8'h43;
            5'd8: rom22 = 8'h7b;
            5'd9: rom22 = 8'h1d;
            5'd10: rom22 = 8'h89;
            5'd11: rom22 = 8'h1c;
            5'd12: rom22 = 8'h28;
            5'd13: rom22 = 8'h45;
            5'd14: rom22 = 8'hbd;
            5'd15: rom22 = 8'h13;
            5'd16: rom22 = 8'hf4;
            5'd17: rom22 = 8'hb6;
            5'd18: rom22 = 8'hb0;
            5'd19: rom22 = 8'h83;
            5'd20: rom22 = 8'hb3;
            5'd21: rom22 = 8'h59;
            default: rom22 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom24;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom24 = 8'h75;
            5'd1: rom24 = 8'h90;
            5'd2: rom24 = 8'hd9;
            5'd3: rom24 = 8'h7f;
            5'd4: rom24 = 8'hf7;
            5'd5: rom24 = 8'hed;
            5'd6: rom24 = 8'h01;
            5'd7: rom24 = 8'hce;
            5'd8: rom24 = 8'h2b;
            5'd9: rom24 = 8'h3d;
            5'd10: rom24 = 8'h48;
            5'd11: rom24 = 8'h82;
            5'd12: rom24 = 8'h49;
            5'd13: rom24 = 8'he5;
            5'd14: rom24 = 8'h96;
            5'd15: rom24 = 8'h73;
            5'd16: rom24 = 8'h66;
            5'd17: rom24 = 8'hd8;
            5'd18: rom24 = 8'hed;
            5'd19: rom24 = 8'hb2;
            5'd20: rom24 = 8'h46;
            5'd21: rom24 = 8'ha9;
            5'd22: rom24 = 8'h76;
            5'd23: rom24 = 8'h7a;
            default: rom24 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom26;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom26 = 8'h5e;
            5'd1: rom26 = 8'h2b;
            5'd2: rom26 = 8'h4d;
            5'd3: rom26 = 8'h92;
            5'd4: rom26 = 8'h90;
            5'd5: rom26 = 8'h46;
            5'd6: rom26 = 8'h44;
            5'd7: rom26 = 8'h87;
            5'd8: rom26 = 8'h2a;
            5'd9: rom26 = 8'he9;
            5'd10: rom26 = 8'h75;
            5'd11: rom26 = 8'hd1;
            5'd12: rom26 = 8'h28;
            5'd13: rom26 = 8'h91;
            5'd14: rom26 = 8'h18;
            5'd15: rom26 = 8'hce;
            5'd16: rom26 = 8'h38;
            5'd17: rom26 = 8'h4d;
            5'd18: rom26 = 8'h98;
            5'd19: rom26 = 8'hc7;
            5'd20: rom26 = 8'h62;
            5'd21: rom26 = 8'h88;
            5'd22: rom26 = 8'h04;
            5'd23: rom26 = 8'hb7;
            5'd24: rom26 = 8'h33;
            5'd25: rom26 = 8'hf6;
            default: rom26 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom28;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom28 = 8'hc5;
            5'd1: rom28 = 8'h3a;
            5'd2: rom28 = 8'h4a;
            5'd3: rom28 = 8'hb0;
            5'd4: rom28 = 8'h93;
            5'd5: rom28 = 8'h79;
            5'd6: rom28 = 8'h64;
            5'd7: rom28 = 8'hb5;
            5'd8: rom28 = 8'h7f;
            5'd9: rom28 = 8'he9;
            5'd10: rom28 = 8'h77;
            5'd11: rom28 = 8'h75;
            5'd12: rom28 = 8'h38;
            5'd13: rom28 = 8'hf7;
            5'd14: rom28 = 8'h0c;
            5'd15: rom28 = 8'ha7;
            5'd16: rom28 = 8'h29;
            5'd17: rom28 = 8'h64;
            5'd18: rom28 = 8'hae;
            5'd19: rom28 = 8'h67;
            5'd20: rom28 = 8'h96;
            5'd21: rom28 = 8'hd0;
            5'd22: rom28 = 8'hfb;
            5'd23: rom28 = 8'h12;
            5'd24: rom28 = 8'h0d;
            5'd25: rom28 = 8'h1c;
            5'd26: rom28 = 8'h09;
            5'd27: rom28 = 8'hfc;
            default: rom28 = 8'h00;
        endcase
    end
endfunction

function [7:0] rom30;
    input [4:0] idx;
    begin
        case (idx)
            5'd0: rom30 = 8'h96;
            5'd1: rom30 = 8'h82;
            5'd2: rom30 = 8'h6a;
            5'd3: rom30 = 8'h0b;
            5'd4: rom30 = 8'hc3;
            5'd5: rom30 = 8'hd8;
            5'd6: rom30 = 8'h4a;
            5'd7: rom30 = 8'he4;
            5'd8: rom30 = 8'h2e;
            5'd9: rom30 = 8'h12;
            5'd10: rom30 = 8'h19;
            5'd11: rom30 = 8'h48;
            5'd12: rom30 = 8'hf6;
            5'd13: rom30 = 8'hb5;
            5'd14: rom30 = 8'h33;
            5'd15: rom30 = 8'h8a;
            5'd16: rom30 = 8'hd9;
            5'd17: rom30 = 8'h16;
            5'd18: rom30 = 8'hb1;
            5'd19: rom30 = 8'h67;
            5'd20: rom30 = 8'h46;
            5'd21: rom30 = 8'h05;
            5'd22: rom30 = 8'h62;
            5'd23: rom30 = 8'h4b;
            5'd24: rom30 = 8'hc0;
            5'd25: rom30 = 8'hc3;
            5'd26: rom30 = 8'h49;
            5'd27: rom30 = 8'h4d;
            5'd28: rom30 = 8'hf6;
            5'd29: rom30 = 8'hd4;
            default: rom30 = 8'h00;
        endcase
    end
endfunction

`endif  // QR_RS_GEN_ROM_VH
