// GENERATED by scripts/gen_tables.py - DO NOT EDIT BY HAND.
// Derived from scripts/golden_model.py (qrcode reference library).
// Included INSIDE modules - no timescale directive allowed here.
// ISO 18004 tables for versions 1-40, all EC levels.
`ifndef QR_TABLES_VH
`define QR_TABLES_VH

// total data codewords (payload capacity) per (version, ec)
function [11:0] tbl_data_cw;
    input [5:0] v;
    input [1:0] ec;
    begin
        case (v)
            6'd1: tbl_data_cw = (ec == 2'd0) ? 12'd19 : (ec == 2'd1) ? 12'd16 : (ec == 2'd2) ? 12'd13 : (ec == 2'd3) ? 12'd9 : 12'd0;
            6'd2: tbl_data_cw = (ec == 2'd0) ? 12'd34 : (ec == 2'd1) ? 12'd28 : (ec == 2'd2) ? 12'd22 : (ec == 2'd3) ? 12'd16 : 12'd0;
            6'd3: tbl_data_cw = (ec == 2'd0) ? 12'd55 : (ec == 2'd1) ? 12'd44 : (ec == 2'd2) ? 12'd34 : (ec == 2'd3) ? 12'd26 : 12'd0;
            6'd4: tbl_data_cw = (ec == 2'd0) ? 12'd80 : (ec == 2'd1) ? 12'd64 : (ec == 2'd2) ? 12'd48 : (ec == 2'd3) ? 12'd36 : 12'd0;
            6'd5: tbl_data_cw = (ec == 2'd0) ? 12'd108 : (ec == 2'd1) ? 12'd86 : (ec == 2'd2) ? 12'd62 : (ec == 2'd3) ? 12'd46 : 12'd0;
            6'd6: tbl_data_cw = (ec == 2'd0) ? 12'd136 : (ec == 2'd1) ? 12'd108 : (ec == 2'd2) ? 12'd76 : (ec == 2'd3) ? 12'd60 : 12'd0;
            6'd7: tbl_data_cw = (ec == 2'd0) ? 12'd156 : (ec == 2'd1) ? 12'd124 : (ec == 2'd2) ? 12'd88 : (ec == 2'd3) ? 12'd66 : 12'd0;
            6'd8: tbl_data_cw = (ec == 2'd0) ? 12'd194 : (ec == 2'd1) ? 12'd154 : (ec == 2'd2) ? 12'd110 : (ec == 2'd3) ? 12'd86 : 12'd0;
            6'd9: tbl_data_cw = (ec == 2'd0) ? 12'd232 : (ec == 2'd1) ? 12'd182 : (ec == 2'd2) ? 12'd132 : (ec == 2'd3) ? 12'd100 : 12'd0;
            6'd10: tbl_data_cw = (ec == 2'd0) ? 12'd274 : (ec == 2'd1) ? 12'd216 : (ec == 2'd2) ? 12'd154 : (ec == 2'd3) ? 12'd122 : 12'd0;
            6'd11: tbl_data_cw = (ec == 2'd0) ? 12'd324 : (ec == 2'd1) ? 12'd254 : (ec == 2'd2) ? 12'd180 : (ec == 2'd3) ? 12'd140 : 12'd0;
            6'd12: tbl_data_cw = (ec == 2'd0) ? 12'd370 : (ec == 2'd1) ? 12'd290 : (ec == 2'd2) ? 12'd206 : (ec == 2'd3) ? 12'd158 : 12'd0;
            6'd13: tbl_data_cw = (ec == 2'd0) ? 12'd428 : (ec == 2'd1) ? 12'd334 : (ec == 2'd2) ? 12'd244 : (ec == 2'd3) ? 12'd180 : 12'd0;
            6'd14: tbl_data_cw = (ec == 2'd0) ? 12'd461 : (ec == 2'd1) ? 12'd365 : (ec == 2'd2) ? 12'd261 : (ec == 2'd3) ? 12'd197 : 12'd0;
            6'd15: tbl_data_cw = (ec == 2'd0) ? 12'd523 : (ec == 2'd1) ? 12'd415 : (ec == 2'd2) ? 12'd295 : (ec == 2'd3) ? 12'd223 : 12'd0;
            6'd16: tbl_data_cw = (ec == 2'd0) ? 12'd589 : (ec == 2'd1) ? 12'd453 : (ec == 2'd2) ? 12'd325 : (ec == 2'd3) ? 12'd253 : 12'd0;
            6'd17: tbl_data_cw = (ec == 2'd0) ? 12'd647 : (ec == 2'd1) ? 12'd507 : (ec == 2'd2) ? 12'd367 : (ec == 2'd3) ? 12'd283 : 12'd0;
            6'd18: tbl_data_cw = (ec == 2'd0) ? 12'd721 : (ec == 2'd1) ? 12'd563 : (ec == 2'd2) ? 12'd397 : (ec == 2'd3) ? 12'd313 : 12'd0;
            6'd19: tbl_data_cw = (ec == 2'd0) ? 12'd795 : (ec == 2'd1) ? 12'd627 : (ec == 2'd2) ? 12'd445 : (ec == 2'd3) ? 12'd341 : 12'd0;
            6'd20: tbl_data_cw = (ec == 2'd0) ? 12'd861 : (ec == 2'd1) ? 12'd669 : (ec == 2'd2) ? 12'd485 : (ec == 2'd3) ? 12'd385 : 12'd0;
            6'd21: tbl_data_cw = (ec == 2'd0) ? 12'd932 : (ec == 2'd1) ? 12'd714 : (ec == 2'd2) ? 12'd512 : (ec == 2'd3) ? 12'd406 : 12'd0;
            6'd22: tbl_data_cw = (ec == 2'd0) ? 12'd1006 : (ec == 2'd1) ? 12'd782 : (ec == 2'd2) ? 12'd568 : (ec == 2'd3) ? 12'd442 : 12'd0;
            6'd23: tbl_data_cw = (ec == 2'd0) ? 12'd1094 : (ec == 2'd1) ? 12'd860 : (ec == 2'd2) ? 12'd614 : (ec == 2'd3) ? 12'd464 : 12'd0;
            6'd24: tbl_data_cw = (ec == 2'd0) ? 12'd1174 : (ec == 2'd1) ? 12'd914 : (ec == 2'd2) ? 12'd664 : (ec == 2'd3) ? 12'd514 : 12'd0;
            6'd25: tbl_data_cw = (ec == 2'd0) ? 12'd1276 : (ec == 2'd1) ? 12'd1000 : (ec == 2'd2) ? 12'd718 : (ec == 2'd3) ? 12'd538 : 12'd0;
            6'd26: tbl_data_cw = (ec == 2'd0) ? 12'd1370 : (ec == 2'd1) ? 12'd1062 : (ec == 2'd2) ? 12'd754 : (ec == 2'd3) ? 12'd596 : 12'd0;
            6'd27: tbl_data_cw = (ec == 2'd0) ? 12'd1468 : (ec == 2'd1) ? 12'd1128 : (ec == 2'd2) ? 12'd808 : (ec == 2'd3) ? 12'd628 : 12'd0;
            6'd28: tbl_data_cw = (ec == 2'd0) ? 12'd1531 : (ec == 2'd1) ? 12'd1193 : (ec == 2'd2) ? 12'd871 : (ec == 2'd3) ? 12'd661 : 12'd0;
            6'd29: tbl_data_cw = (ec == 2'd0) ? 12'd1631 : (ec == 2'd1) ? 12'd1267 : (ec == 2'd2) ? 12'd911 : (ec == 2'd3) ? 12'd701 : 12'd0;
            6'd30: tbl_data_cw = (ec == 2'd0) ? 12'd1735 : (ec == 2'd1) ? 12'd1373 : (ec == 2'd2) ? 12'd985 : (ec == 2'd3) ? 12'd745 : 12'd0;
            6'd31: tbl_data_cw = (ec == 2'd0) ? 12'd1843 : (ec == 2'd1) ? 12'd1455 : (ec == 2'd2) ? 12'd1033 : (ec == 2'd3) ? 12'd793 : 12'd0;
            6'd32: tbl_data_cw = (ec == 2'd0) ? 12'd1955 : (ec == 2'd1) ? 12'd1541 : (ec == 2'd2) ? 12'd1115 : (ec == 2'd3) ? 12'd845 : 12'd0;
            6'd33: tbl_data_cw = (ec == 2'd0) ? 12'd2071 : (ec == 2'd1) ? 12'd1631 : (ec == 2'd2) ? 12'd1171 : (ec == 2'd3) ? 12'd901 : 12'd0;
            6'd34: tbl_data_cw = (ec == 2'd0) ? 12'd2191 : (ec == 2'd1) ? 12'd1725 : (ec == 2'd2) ? 12'd1231 : (ec == 2'd3) ? 12'd961 : 12'd0;
            6'd35: tbl_data_cw = (ec == 2'd0) ? 12'd2306 : (ec == 2'd1) ? 12'd1812 : (ec == 2'd2) ? 12'd1286 : (ec == 2'd3) ? 12'd986 : 12'd0;
            6'd36: tbl_data_cw = (ec == 2'd0) ? 12'd2434 : (ec == 2'd1) ? 12'd1914 : (ec == 2'd2) ? 12'd1354 : (ec == 2'd3) ? 12'd1054 : 12'd0;
            6'd37: tbl_data_cw = (ec == 2'd0) ? 12'd2566 : (ec == 2'd1) ? 12'd1992 : (ec == 2'd2) ? 12'd1426 : (ec == 2'd3) ? 12'd1096 : 12'd0;
            6'd38: tbl_data_cw = (ec == 2'd0) ? 12'd2702 : (ec == 2'd1) ? 12'd2102 : (ec == 2'd2) ? 12'd1502 : (ec == 2'd3) ? 12'd1142 : 12'd0;
            6'd39: tbl_data_cw = (ec == 2'd0) ? 12'd2812 : (ec == 2'd1) ? 12'd2216 : (ec == 2'd2) ? 12'd1582 : (ec == 2'd3) ? 12'd1222 : 12'd0;
            6'd40: tbl_data_cw = (ec == 2'd0) ? 12'd2956 : (ec == 2'd1) ? 12'd2334 : (ec == 2'd2) ? 12'd1666 : (ec == 2'd3) ? 12'd1276 : 12'd0;
            default: tbl_data_cw = 12'd0;
        endcase
    end
endfunction

// total codewords (data + ecc) per (version, ec)
function [11:0] tbl_total_cw;
    input [5:0] v;
    input [1:0] ec;
    begin
        case (v)
            6'd1: tbl_total_cw = (ec == 2'd0) ? 12'd26 : (ec == 2'd1) ? 12'd26 : (ec == 2'd2) ? 12'd26 : (ec == 2'd3) ? 12'd26 : 12'd0;
            6'd2: tbl_total_cw = (ec == 2'd0) ? 12'd44 : (ec == 2'd1) ? 12'd44 : (ec == 2'd2) ? 12'd44 : (ec == 2'd3) ? 12'd44 : 12'd0;
            6'd3: tbl_total_cw = (ec == 2'd0) ? 12'd70 : (ec == 2'd1) ? 12'd70 : (ec == 2'd2) ? 12'd70 : (ec == 2'd3) ? 12'd70 : 12'd0;
            6'd4: tbl_total_cw = (ec == 2'd0) ? 12'd100 : (ec == 2'd1) ? 12'd100 : (ec == 2'd2) ? 12'd100 : (ec == 2'd3) ? 12'd100 : 12'd0;
            6'd5: tbl_total_cw = (ec == 2'd0) ? 12'd134 : (ec == 2'd1) ? 12'd134 : (ec == 2'd2) ? 12'd134 : (ec == 2'd3) ? 12'd134 : 12'd0;
            6'd6: tbl_total_cw = (ec == 2'd0) ? 12'd172 : (ec == 2'd1) ? 12'd172 : (ec == 2'd2) ? 12'd172 : (ec == 2'd3) ? 12'd172 : 12'd0;
            6'd7: tbl_total_cw = (ec == 2'd0) ? 12'd196 : (ec == 2'd1) ? 12'd196 : (ec == 2'd2) ? 12'd196 : (ec == 2'd3) ? 12'd196 : 12'd0;
            6'd8: tbl_total_cw = (ec == 2'd0) ? 12'd242 : (ec == 2'd1) ? 12'd242 : (ec == 2'd2) ? 12'd242 : (ec == 2'd3) ? 12'd242 : 12'd0;
            6'd9: tbl_total_cw = (ec == 2'd0) ? 12'd292 : (ec == 2'd1) ? 12'd292 : (ec == 2'd2) ? 12'd292 : (ec == 2'd3) ? 12'd292 : 12'd0;
            6'd10: tbl_total_cw = (ec == 2'd0) ? 12'd346 : (ec == 2'd1) ? 12'd346 : (ec == 2'd2) ? 12'd346 : (ec == 2'd3) ? 12'd346 : 12'd0;
            6'd11: tbl_total_cw = (ec == 2'd0) ? 12'd404 : (ec == 2'd1) ? 12'd404 : (ec == 2'd2) ? 12'd404 : (ec == 2'd3) ? 12'd404 : 12'd0;
            6'd12: tbl_total_cw = (ec == 2'd0) ? 12'd466 : (ec == 2'd1) ? 12'd466 : (ec == 2'd2) ? 12'd466 : (ec == 2'd3) ? 12'd466 : 12'd0;
            6'd13: tbl_total_cw = (ec == 2'd0) ? 12'd532 : (ec == 2'd1) ? 12'd532 : (ec == 2'd2) ? 12'd532 : (ec == 2'd3) ? 12'd532 : 12'd0;
            6'd14: tbl_total_cw = (ec == 2'd0) ? 12'd581 : (ec == 2'd1) ? 12'd581 : (ec == 2'd2) ? 12'd581 : (ec == 2'd3) ? 12'd581 : 12'd0;
            6'd15: tbl_total_cw = (ec == 2'd0) ? 12'd655 : (ec == 2'd1) ? 12'd655 : (ec == 2'd2) ? 12'd655 : (ec == 2'd3) ? 12'd655 : 12'd0;
            6'd16: tbl_total_cw = (ec == 2'd0) ? 12'd733 : (ec == 2'd1) ? 12'd733 : (ec == 2'd2) ? 12'd733 : (ec == 2'd3) ? 12'd733 : 12'd0;
            6'd17: tbl_total_cw = (ec == 2'd0) ? 12'd815 : (ec == 2'd1) ? 12'd815 : (ec == 2'd2) ? 12'd815 : (ec == 2'd3) ? 12'd815 : 12'd0;
            6'd18: tbl_total_cw = (ec == 2'd0) ? 12'd901 : (ec == 2'd1) ? 12'd901 : (ec == 2'd2) ? 12'd901 : (ec == 2'd3) ? 12'd901 : 12'd0;
            6'd19: tbl_total_cw = (ec == 2'd0) ? 12'd991 : (ec == 2'd1) ? 12'd991 : (ec == 2'd2) ? 12'd991 : (ec == 2'd3) ? 12'd991 : 12'd0;
            6'd20: tbl_total_cw = (ec == 2'd0) ? 12'd1085 : (ec == 2'd1) ? 12'd1085 : (ec == 2'd2) ? 12'd1085 : (ec == 2'd3) ? 12'd1085 : 12'd0;
            6'd21: tbl_total_cw = (ec == 2'd0) ? 12'd1156 : (ec == 2'd1) ? 12'd1156 : (ec == 2'd2) ? 12'd1156 : (ec == 2'd3) ? 12'd1156 : 12'd0;
            6'd22: tbl_total_cw = (ec == 2'd0) ? 12'd1258 : (ec == 2'd1) ? 12'd1258 : (ec == 2'd2) ? 12'd1258 : (ec == 2'd3) ? 12'd1258 : 12'd0;
            6'd23: tbl_total_cw = (ec == 2'd0) ? 12'd1364 : (ec == 2'd1) ? 12'd1364 : (ec == 2'd2) ? 12'd1364 : (ec == 2'd3) ? 12'd1364 : 12'd0;
            6'd24: tbl_total_cw = (ec == 2'd0) ? 12'd1474 : (ec == 2'd1) ? 12'd1474 : (ec == 2'd2) ? 12'd1474 : (ec == 2'd3) ? 12'd1474 : 12'd0;
            6'd25: tbl_total_cw = (ec == 2'd0) ? 12'd1588 : (ec == 2'd1) ? 12'd1588 : (ec == 2'd2) ? 12'd1588 : (ec == 2'd3) ? 12'd1588 : 12'd0;
            6'd26: tbl_total_cw = (ec == 2'd0) ? 12'd1706 : (ec == 2'd1) ? 12'd1706 : (ec == 2'd2) ? 12'd1706 : (ec == 2'd3) ? 12'd1706 : 12'd0;
            6'd27: tbl_total_cw = (ec == 2'd0) ? 12'd1828 : (ec == 2'd1) ? 12'd1828 : (ec == 2'd2) ? 12'd1828 : (ec == 2'd3) ? 12'd1828 : 12'd0;
            6'd28: tbl_total_cw = (ec == 2'd0) ? 12'd1921 : (ec == 2'd1) ? 12'd1921 : (ec == 2'd2) ? 12'd1921 : (ec == 2'd3) ? 12'd1921 : 12'd0;
            6'd29: tbl_total_cw = (ec == 2'd0) ? 12'd2051 : (ec == 2'd1) ? 12'd2051 : (ec == 2'd2) ? 12'd2051 : (ec == 2'd3) ? 12'd2051 : 12'd0;
            6'd30: tbl_total_cw = (ec == 2'd0) ? 12'd2185 : (ec == 2'd1) ? 12'd2185 : (ec == 2'd2) ? 12'd2185 : (ec == 2'd3) ? 12'd2185 : 12'd0;
            6'd31: tbl_total_cw = (ec == 2'd0) ? 12'd2323 : (ec == 2'd1) ? 12'd2323 : (ec == 2'd2) ? 12'd2323 : (ec == 2'd3) ? 12'd2323 : 12'd0;
            6'd32: tbl_total_cw = (ec == 2'd0) ? 12'd2465 : (ec == 2'd1) ? 12'd2465 : (ec == 2'd2) ? 12'd2465 : (ec == 2'd3) ? 12'd2465 : 12'd0;
            6'd33: tbl_total_cw = (ec == 2'd0) ? 12'd2611 : (ec == 2'd1) ? 12'd2611 : (ec == 2'd2) ? 12'd2611 : (ec == 2'd3) ? 12'd2611 : 12'd0;
            6'd34: tbl_total_cw = (ec == 2'd0) ? 12'd2761 : (ec == 2'd1) ? 12'd2761 : (ec == 2'd2) ? 12'd2761 : (ec == 2'd3) ? 12'd2761 : 12'd0;
            6'd35: tbl_total_cw = (ec == 2'd0) ? 12'd2876 : (ec == 2'd1) ? 12'd2876 : (ec == 2'd2) ? 12'd2876 : (ec == 2'd3) ? 12'd2876 : 12'd0;
            6'd36: tbl_total_cw = (ec == 2'd0) ? 12'd3034 : (ec == 2'd1) ? 12'd3034 : (ec == 2'd2) ? 12'd3034 : (ec == 2'd3) ? 12'd3034 : 12'd0;
            6'd37: tbl_total_cw = (ec == 2'd0) ? 12'd3196 : (ec == 2'd1) ? 12'd3196 : (ec == 2'd2) ? 12'd3196 : (ec == 2'd3) ? 12'd3196 : 12'd0;
            6'd38: tbl_total_cw = (ec == 2'd0) ? 12'd3362 : (ec == 2'd1) ? 12'd3362 : (ec == 2'd2) ? 12'd3362 : (ec == 2'd3) ? 12'd3362 : 12'd0;
            6'd39: tbl_total_cw = (ec == 2'd0) ? 12'd3532 : (ec == 2'd1) ? 12'd3532 : (ec == 2'd2) ? 12'd3532 : (ec == 2'd3) ? 12'd3532 : 12'd0;
            6'd40: tbl_total_cw = (ec == 2'd0) ? 12'd3706 : (ec == 2'd1) ? 12'd3706 : (ec == 2'd2) ? 12'd3706 : (ec == 2'd3) ? 12'd3706 : 12'd0;
            default: tbl_total_cw = 12'd0;
        endcase
    end
endfunction

// block layout per (version, ec):
//   {d1[6:0], n1[6:0], d2[6:0], n2[6:0], ecc[4:0]}
// n1 blocks carry d1 data codewords, n2 blocks carry d2 (d2 = d1+1
// whenever n2 > 0); ecc is uniform across all blocks of a version.
function [32:0] tbl_blocks;
    input [5:0] v;
    input [1:0] ec;
    reg [32:0] r;
    begin
        case (v)
            6'd1: r = (ec == 2'd0) ? 33'h4c080007 : (ec == 2'd1) ? 33'h4008000a : (ec == 2'd2) ? 33'h3408000d : (ec == 2'd3) ? 33'h24080011 : 33'h0;
            6'd2: r = (ec == 2'd0) ? 33'h8808000a : (ec == 2'd1) ? 33'h70080010 : (ec == 2'd2) ? 33'h58080016 : (ec == 2'd3) ? 33'h4008001c : 33'h0;
            6'd3: r = (ec == 2'd0) ? 33'hdc08000f : (ec == 2'd1) ? 33'hb008001a : (ec == 2'd2) ? 33'h44100012 : (ec == 2'd3) ? 33'h34100016 : 33'h0;
            6'd4: r = (ec == 2'd0) ? 33'h140080014 : (ec == 2'd1) ? 33'h80100012 : (ec == 2'd2) ? 33'h6010001a : (ec == 2'd3) ? 33'h24200010 : 33'h0;
            6'd5: r = (ec == 2'd0) ? 33'h1b008001a : (ec == 2'd1) ? 33'hac100018 : (ec == 2'd2) ? 33'h3c110052 : (ec == 2'd3) ? 33'h2c10c056 : 33'h0;
            6'd6: r = (ec == 2'd0) ? 33'h110100012 : (ec == 2'd1) ? 33'h6c200010 : (ec == 2'd2) ? 33'h4c200018 : (ec == 2'd3) ? 33'h3c20001c : 33'h0;
            6'd7: r = (ec == 2'd0) ? 33'h138100014 : (ec == 2'd1) ? 33'h7c200012 : (ec == 2'd2) ? 33'h3810f092 : (ec == 2'd3) ? 33'h3420e03a : 33'h0;
            6'd8: r = (ec == 2'd0) ? 33'h184100018 : (ec == 2'd1) ? 33'h98127056 : (ec == 2'd2) ? 33'h48213056 : (ec == 2'd3) ? 33'h3820f05a : 33'h0;
            6'd9: r = (ec == 2'd0) ? 33'h1d010001e : (ec == 2'd1) ? 33'h901a5056 : (ec == 2'd2) ? 33'h40211094 : (ec == 2'd3) ? 33'h3020d098 : 33'h0;
            6'd10: r = (ec == 2'd0) ? 33'h110145052 : (ec == 2'd1) ? 33'hac22c03a : (ec == 2'd2) ? 33'h4c314058 : (ec == 2'd3) ? 33'h3c31005c : 33'h0;
            6'd11: r = (ec == 2'd0) ? 33'h144200014 : (ec == 2'd1) ? 33'hc80b309e : (ec == 2'd2) ? 33'h5821709c : (ec == 2'd3) ? 33'h3018d118 : 33'h0;
            6'd12: r = (ec == 2'd0) ? 33'h17015d058 : (ec == 2'd1) ? 33'h90325056 : (ec == 2'd2) ? 33'h502150da : (ec == 2'd3) ? 33'h3838f09c : 33'h0;
            6'd13: r = (ec == 2'd0) ? 33'h1ac20001a : (ec == 2'd1) ? 33'h94426036 : (ec == 2'd2) ? 33'h50415098 : (ec == 2'd3) ? 33'h2c60c096 : 33'h0;
            6'd14: r = (ec == 2'd0) ? 33'h1cc1f403e : (ec == 2'd1) ? 33'ha02290b8 : (ec == 2'd2) ? 33'h405910b4 : (ec == 2'd3) ? 33'h3058d0b8 : 33'h0;
            6'd15: r = (ec == 2'd0) ? 33'h15c2d8036 : (ec == 2'd1) ? 33'ha42aa0b8 : (ec == 2'd2) ? 33'h602990fe : (ec == 2'd3) ? 33'h3058d0f8 : 33'h0;
            6'd16: r = (ec == 2'd0) ? 33'h1882e3038 : (ec == 2'd1) ? 33'hb43ae07c : (ec == 2'd2) ? 33'h4c794058 : (ec == 2'd3) ? 33'h3c1901be : 33'h0;
            6'd17: r = (ec == 2'd0) ? 33'h1ac0ec0bc : (ec == 2'd1) ? 33'hb852f03c : (ec == 2'd2) ? 33'h580971fc : (ec == 2'd3) ? 33'h3810f23c : 33'h0;
            6'd18: r = (ec == 2'd0) ? 33'h1e02f903e : (ec == 2'd1) ? 33'hac4ac09a : (ec == 2'd2) ? 33'h5889703c : (ec == 2'd3) ? 33'h3810f27c : 33'h0;
            6'd19: r = (ec == 2'd0) ? 33'h1c41f209c : (ec == 2'd1) ? 33'hb01ad17a : (ec == 2'd2) ? 33'h5489609a : (ec == 2'd3) ? 33'h3448e21a : 33'h0;
            6'd20: r = (ec == 2'd0) ? 33'h1ac1ec0bc : (ec == 2'd1) ? 33'ha41aa1ba : (ec == 2'd2) ? 33'h607990be : (ec == 2'd3) ? 33'h3c79015c : 33'h0;
            6'd21: r = (ec == 2'd0) ? 33'h1d027509c : (ec == 2'd1) ? 33'ha888001a : (ec == 2'd2) ? 33'h588970dc : (ec == 2'd3) ? 33'h409910de : 33'h0;
            6'd22: r = (ec == 2'd0) ? 33'h1bc1700fc : (ec == 2'd1) ? 33'hb888001c : (ec == 2'd2) ? 33'h6039921e : (ec == 2'd3) ? 33'h35100018 : 33'h0;
            6'd23: r = (ec == 2'd0) ? 33'h1e427a0be : (ec == 2'd1) ? 33'hbc2301dc : (ec == 2'd2) ? 33'h605991de : (ec == 2'd3) ? 33'h3c8101de : 33'h0;
            6'd24: r = (ec == 2'd0) ? 33'h1d437609e : (ec == 2'd1) ? 33'hb432e1dc : (ec == 2'd2) ? 33'h6059921e : (ec == 2'd3) ? 33'h40f1105e : 33'h0;
            6'd25: r = (ec == 2'd0) ? 33'h1a846b09a : (ec == 2'd1) ? 33'hbc4301bc : (ec == 2'd2) ? 33'h603992de : (ec == 2'd3) ? 33'h3cb101be : 33'h0;
            6'd26: r = (ec == 2'd0) ? 33'h1c857305c : (ec == 2'd1) ? 33'hb89af09c : (ec == 2'd2) ? 33'h58e170dc : (ec == 2'd3) ? 33'h4109109e : 33'h0;
            6'd27: r = (ec == 2'd0) ? 33'h1e847b09e : (ec == 2'd1) ? 33'hb4b2e07c : (ec == 2'd2) ? 33'h5c41835e : (ec == 2'd3) ? 33'h3c61039e : 33'h0;
            6'd28: r = (ec == 2'd0) ? 33'h1d41f615e : (ec == 2'd1) ? 33'hb41ae2fc : (ec == 2'd2) ? 33'h602193fe : (ec == 2'd3) ? 33'h3c5903fe : 33'h0;
            6'd29: r = (ec == 2'd0) ? 33'h1d03f50fe : (ec == 2'd1) ? 33'hb4aae0fc : (ec == 2'd2) ? 33'h5c0984be : (ec == 2'd3) ? 33'h3c99035e : 33'h0;
            6'd30: r = (ec == 2'd0) ? 33'h1cc2f415e : (ec == 2'd1) ? 33'hbc9b015c : (ec == 2'd2) ? 33'h6079933e : (ec == 2'd3) ? 33'h3cb9033e : 33'h0;
            6'd31: r = (ec == 2'd0) ? 33'h1cc6f407e : (ec == 2'd1) ? 33'hb812f3bc : (ec == 2'd2) ? 33'h6151903e : (ec == 2'd3) ? 33'h3cb9039e : 33'h0;
            6'd32: r = (ec == 2'd0) ? 33'h1cc88001e : (ec == 2'd1) ? 33'hb852f2fc : (ec == 2'd2) ? 33'h6051947e : (ec == 2'd3) ? 33'h3c99047e : 33'h0;
            6'd33: r = (ec == 2'd0) ? 33'h1cc8f403e : (ec == 2'd1) ? 33'hb872f2bc : (ec == 2'd2) ? 33'h60e9927e : (ec == 2'd3) ? 33'h3c5905de : 33'h0;
            6'd34: r = (ec == 2'd0) ? 33'h1cc6f40de : (ec == 2'd1) ? 33'hb872f2fc : (ec == 2'd2) ? 33'h616190fe : (ec == 2'd3) ? 33'h41d9103e : 33'h0;
            6'd35: r = (ec == 2'd0) ? 33'h1e467a0fe : (ec == 2'd1) ? 33'hbc63035c : (ec == 2'd2) ? 33'h613991de : (ec == 2'd3) ? 33'h3cb1053e : 33'h0;
            6'd36: r = (ec == 2'd0) ? 33'h1e437a1de : (ec == 2'd1) ? 33'hbc33045c : (ec == 2'd2) ? 33'h6171915e : (ec == 2'd3) ? 33'h3c11081e : 33'h0;
            6'd37: r = (ec == 2'd0) ? 33'h1e88fb09e : (ec == 2'd1) ? 33'hb8eaf1dc : (ec == 2'd2) ? 33'h6189915e : (ec == 2'd3) ? 33'h3cc105de : 33'h0;
            6'd38: r = (ec == 2'd0) ? 33'h1e827b25e : (ec == 2'd1) ? 33'hb86af41c : (ec == 2'd2) ? 33'h618191de : (ec == 2'd3) ? 33'h3d51041e : 33'h0;
            6'd39: r = (ec == 2'd0) ? 33'h1d4a7609e : (ec == 2'd1) ? 33'hbd4300fc : (ec == 2'd2) ? 33'h615992de : (ec == 2'd3) ? 33'h3c51087e : 33'h0;
            6'd40: r = (ec == 2'd0) ? 33'h1d89f70de : (ec == 2'd1) ? 33'hbc9303fc : (ec == 2'd2) ? 33'h6111945e : (ec == 2'd3) ? 33'h3ca107be : 33'h0;
            default: r = 33'h0;
        endcase
        tbl_blocks = r;
    end
endfunction

// alignment-pattern centres: tbl_align_pos(v, i) for i < tbl_nalign(v)
function [2:0] tbl_nalign;
    input [5:0] v;
    begin
        case (v)
            6'd1: tbl_nalign = 3'd0;
            6'd2: tbl_nalign = 3'd2;
            6'd3: tbl_nalign = 3'd2;
            6'd4: tbl_nalign = 3'd2;
            6'd5: tbl_nalign = 3'd2;
            6'd6: tbl_nalign = 3'd2;
            6'd7: tbl_nalign = 3'd3;
            6'd8: tbl_nalign = 3'd3;
            6'd9: tbl_nalign = 3'd3;
            6'd10: tbl_nalign = 3'd3;
            6'd11: tbl_nalign = 3'd3;
            6'd12: tbl_nalign = 3'd3;
            6'd13: tbl_nalign = 3'd3;
            6'd14: tbl_nalign = 3'd4;
            6'd15: tbl_nalign = 3'd4;
            6'd16: tbl_nalign = 3'd4;
            6'd17: tbl_nalign = 3'd4;
            6'd18: tbl_nalign = 3'd4;
            6'd19: tbl_nalign = 3'd4;
            6'd20: tbl_nalign = 3'd4;
            6'd21: tbl_nalign = 3'd5;
            6'd22: tbl_nalign = 3'd5;
            6'd23: tbl_nalign = 3'd5;
            6'd24: tbl_nalign = 3'd5;
            6'd25: tbl_nalign = 3'd5;
            6'd26: tbl_nalign = 3'd5;
            6'd27: tbl_nalign = 3'd5;
            6'd28: tbl_nalign = 3'd6;
            6'd29: tbl_nalign = 3'd6;
            6'd30: tbl_nalign = 3'd6;
            6'd31: tbl_nalign = 3'd6;
            6'd32: tbl_nalign = 3'd6;
            6'd33: tbl_nalign = 3'd6;
            6'd34: tbl_nalign = 3'd6;
            6'd35: tbl_nalign = 3'd7;
            6'd36: tbl_nalign = 3'd7;
            6'd37: tbl_nalign = 3'd7;
            6'd38: tbl_nalign = 3'd7;
            6'd39: tbl_nalign = 3'd7;
            6'd40: tbl_nalign = 3'd7;
            default: tbl_nalign = 3'd0;
        endcase
    end
endfunction

function [7:0] tbl_align_pos;
    input [5:0] v;
    input [2:0] i;
    begin
        case (v)
            6'd2: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd18; default: tbl_align_pos = 8'd0; endcase
            6'd3: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd22; default: tbl_align_pos = 8'd0; endcase
            6'd4: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; default: tbl_align_pos = 8'd0; endcase
            6'd5: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; default: tbl_align_pos = 8'd0; endcase
            6'd6: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; default: tbl_align_pos = 8'd0; endcase
            6'd7: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd22; 3'd2: tbl_align_pos = 8'd38; default: tbl_align_pos = 8'd0; endcase
            6'd8: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd24; 3'd2: tbl_align_pos = 8'd42; default: tbl_align_pos = 8'd0; endcase
            6'd9: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd46; default: tbl_align_pos = 8'd0; endcase
            6'd10: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd28; 3'd2: tbl_align_pos = 8'd50; default: tbl_align_pos = 8'd0; endcase
            6'd11: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd54; default: tbl_align_pos = 8'd0; endcase
            6'd12: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd32; 3'd2: tbl_align_pos = 8'd58; default: tbl_align_pos = 8'd0; endcase
            6'd13: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; 3'd2: tbl_align_pos = 8'd62; default: tbl_align_pos = 8'd0; endcase
            6'd14: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd46; 3'd3: tbl_align_pos = 8'd66; default: tbl_align_pos = 8'd0; endcase
            6'd15: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd48; 3'd3: tbl_align_pos = 8'd70; default: tbl_align_pos = 8'd0; endcase
            6'd16: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd50; 3'd3: tbl_align_pos = 8'd74; default: tbl_align_pos = 8'd0; endcase
            6'd17: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd78; default: tbl_align_pos = 8'd0; endcase
            6'd18: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd56; 3'd3: tbl_align_pos = 8'd82; default: tbl_align_pos = 8'd0; endcase
            6'd19: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd86; default: tbl_align_pos = 8'd0; endcase
            6'd20: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; 3'd2: tbl_align_pos = 8'd62; 3'd3: tbl_align_pos = 8'd90; default: tbl_align_pos = 8'd0; endcase
            6'd21: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd28; 3'd2: tbl_align_pos = 8'd50; 3'd3: tbl_align_pos = 8'd72; 3'd4: tbl_align_pos = 8'd94; default: tbl_align_pos = 8'd0; endcase
            6'd22: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd50; 3'd3: tbl_align_pos = 8'd74; 3'd4: tbl_align_pos = 8'd98; default: tbl_align_pos = 8'd0; endcase
            6'd23: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd78; 3'd4: tbl_align_pos = 8'd102; default: tbl_align_pos = 8'd0; endcase
            6'd24: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd28; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd80; 3'd4: tbl_align_pos = 8'd106; default: tbl_align_pos = 8'd0; endcase
            6'd25: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd32; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd84; 3'd4: tbl_align_pos = 8'd110; default: tbl_align_pos = 8'd0; endcase
            6'd26: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd86; 3'd4: tbl_align_pos = 8'd114; default: tbl_align_pos = 8'd0; endcase
            6'd27: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; 3'd2: tbl_align_pos = 8'd62; 3'd3: tbl_align_pos = 8'd90; 3'd4: tbl_align_pos = 8'd118; default: tbl_align_pos = 8'd0; endcase
            6'd28: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd50; 3'd3: tbl_align_pos = 8'd74; 3'd4: tbl_align_pos = 8'd98; 3'd5: tbl_align_pos = 8'd122; default: tbl_align_pos = 8'd0; endcase
            6'd29: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd78; 3'd4: tbl_align_pos = 8'd102; 3'd5: tbl_align_pos = 8'd126; default: tbl_align_pos = 8'd0; endcase
            6'd30: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd52; 3'd3: tbl_align_pos = 8'd78; 3'd4: tbl_align_pos = 8'd104; 3'd5: tbl_align_pos = 8'd130; default: tbl_align_pos = 8'd0; endcase
            6'd31: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd56; 3'd3: tbl_align_pos = 8'd82; 3'd4: tbl_align_pos = 8'd108; 3'd5: tbl_align_pos = 8'd134; default: tbl_align_pos = 8'd0; endcase
            6'd32: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; 3'd2: tbl_align_pos = 8'd60; 3'd3: tbl_align_pos = 8'd86; 3'd4: tbl_align_pos = 8'd112; 3'd5: tbl_align_pos = 8'd138; default: tbl_align_pos = 8'd0; endcase
            6'd33: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd86; 3'd4: tbl_align_pos = 8'd114; 3'd5: tbl_align_pos = 8'd142; default: tbl_align_pos = 8'd0; endcase
            6'd34: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd34; 3'd2: tbl_align_pos = 8'd62; 3'd3: tbl_align_pos = 8'd90; 3'd4: tbl_align_pos = 8'd118; 3'd5: tbl_align_pos = 8'd146; default: tbl_align_pos = 8'd0; endcase
            6'd35: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd78; 3'd4: tbl_align_pos = 8'd102; 3'd5: tbl_align_pos = 8'd126; 3'd6: tbl_align_pos = 8'd150; default: tbl_align_pos = 8'd0; endcase
            6'd36: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd24; 3'd2: tbl_align_pos = 8'd50; 3'd3: tbl_align_pos = 8'd76; 3'd4: tbl_align_pos = 8'd102; 3'd5: tbl_align_pos = 8'd128; 3'd6: tbl_align_pos = 8'd154; default: tbl_align_pos = 8'd0; endcase
            6'd37: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd28; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd80; 3'd4: tbl_align_pos = 8'd106; 3'd5: tbl_align_pos = 8'd132; 3'd6: tbl_align_pos = 8'd158; default: tbl_align_pos = 8'd0; endcase
            6'd38: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd32; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd84; 3'd4: tbl_align_pos = 8'd110; 3'd5: tbl_align_pos = 8'd136; 3'd6: tbl_align_pos = 8'd162; default: tbl_align_pos = 8'd0; endcase
            6'd39: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd26; 3'd2: tbl_align_pos = 8'd54; 3'd3: tbl_align_pos = 8'd82; 3'd4: tbl_align_pos = 8'd110; 3'd5: tbl_align_pos = 8'd138; 3'd6: tbl_align_pos = 8'd166; default: tbl_align_pos = 8'd0; endcase
            6'd40: case (i) 3'd0: tbl_align_pos = 8'd6; 3'd1: tbl_align_pos = 8'd30; 3'd2: tbl_align_pos = 8'd58; 3'd3: tbl_align_pos = 8'd86; 3'd4: tbl_align_pos = 8'd114; 3'd5: tbl_align_pos = 8'd142; 3'd6: tbl_align_pos = 8'd170; default: tbl_align_pos = 8'd0; endcase
            default: tbl_align_pos = 8'd0;
        endcase
    end
endfunction

// remainder bits after the last data codeword
function [2:0] tbl_remainder;
    input [5:0] v;
    begin
        case (v)
            6'd1: tbl_remainder = 3'd0;
            6'd2: tbl_remainder = 3'd7;
            6'd3: tbl_remainder = 3'd7;
            6'd4: tbl_remainder = 3'd7;
            6'd5: tbl_remainder = 3'd7;
            6'd6: tbl_remainder = 3'd7;
            6'd7: tbl_remainder = 3'd0;
            6'd8: tbl_remainder = 3'd0;
            6'd9: tbl_remainder = 3'd0;
            6'd10: tbl_remainder = 3'd0;
            6'd11: tbl_remainder = 3'd0;
            6'd12: tbl_remainder = 3'd0;
            6'd13: tbl_remainder = 3'd0;
            6'd14: tbl_remainder = 3'd3;
            6'd15: tbl_remainder = 3'd3;
            6'd16: tbl_remainder = 3'd3;
            6'd17: tbl_remainder = 3'd3;
            6'd18: tbl_remainder = 3'd3;
            6'd19: tbl_remainder = 3'd3;
            6'd20: tbl_remainder = 3'd3;
            6'd21: tbl_remainder = 3'd4;
            6'd22: tbl_remainder = 3'd4;
            6'd23: tbl_remainder = 3'd4;
            6'd24: tbl_remainder = 3'd4;
            6'd25: tbl_remainder = 3'd4;
            6'd26: tbl_remainder = 3'd4;
            6'd27: tbl_remainder = 3'd4;
            6'd28: tbl_remainder = 3'd3;
            6'd29: tbl_remainder = 3'd3;
            6'd30: tbl_remainder = 3'd3;
            6'd31: tbl_remainder = 3'd3;
            6'd32: tbl_remainder = 3'd3;
            6'd33: tbl_remainder = 3'd3;
            6'd34: tbl_remainder = 3'd3;
            6'd35: tbl_remainder = 3'd0;
            6'd36: tbl_remainder = 3'd0;
            6'd37: tbl_remainder = 3'd0;
            6'd38: tbl_remainder = 3'd0;
            6'd39: tbl_remainder = 3'd0;
            6'd40: tbl_remainder = 3'd0;
            default: tbl_remainder = 3'd0;
        endcase
    end
endfunction

// char-count field width per (version, mode);
// mode: 0 = byte, 1 = numeric, 2 = alphanumeric, 3 = kanji
function [4:0] tbl_cnt_bits;
    input [5:0] v;
    input [1:0] mode;
    begin
        case (v)
            6'd1: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd2: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd3: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd4: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd5: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd6: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd7: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd8: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd9: tbl_cnt_bits = (mode == 2'd1) ? 5'd10 : (mode == 2'd2) ? 5'd9 : (mode == 2'd3) ? 5'd8 : 5'd8;
            6'd10: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd11: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd12: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd13: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd14: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd15: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd16: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd17: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd18: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd19: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd20: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd21: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd22: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd23: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd24: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd25: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd26: tbl_cnt_bits = (mode == 2'd1) ? 5'd12 : (mode == 2'd2) ? 5'd11 : (mode == 2'd3) ? 5'd10 : 5'd16;
            6'd27: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd28: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd29: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd30: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd31: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd32: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd33: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd34: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd35: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd36: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd37: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd38: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd39: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            6'd40: tbl_cnt_bits = (mode == 2'd1) ? 5'd14 : (mode == 2'd2) ? 5'd13 : (mode == 2'd3) ? 5'd12 : 5'd16;
            default: tbl_cnt_bits = 5'd8;
        endcase
    end
endfunction

// 18-bit version information (6 data + 12 BCH, G18 = 0x1F25);
// only defined for versions >= 7
function [17:0] tbl_ver_info;
    input [5:0] v;
    begin
        case (v)
            6'd7: tbl_ver_info = 18'h07c94;
            6'd8: tbl_ver_info = 18'h085bc;
            6'd9: tbl_ver_info = 18'h09a99;
            6'd10: tbl_ver_info = 18'h0a4d3;
            6'd11: tbl_ver_info = 18'h0bbf6;
            6'd12: tbl_ver_info = 18'h0c762;
            6'd13: tbl_ver_info = 18'h0d847;
            6'd14: tbl_ver_info = 18'h0e60d;
            6'd15: tbl_ver_info = 18'h0f928;
            6'd16: tbl_ver_info = 18'h10b78;
            6'd17: tbl_ver_info = 18'h1145d;
            6'd18: tbl_ver_info = 18'h12a17;
            6'd19: tbl_ver_info = 18'h13532;
            6'd20: tbl_ver_info = 18'h149a6;
            6'd21: tbl_ver_info = 18'h15683;
            6'd22: tbl_ver_info = 18'h168c9;
            6'd23: tbl_ver_info = 18'h177ec;
            6'd24: tbl_ver_info = 18'h18ec4;
            6'd25: tbl_ver_info = 18'h191e1;
            6'd26: tbl_ver_info = 18'h1afab;
            6'd27: tbl_ver_info = 18'h1b08e;
            6'd28: tbl_ver_info = 18'h1cc1a;
            6'd29: tbl_ver_info = 18'h1d33f;
            6'd30: tbl_ver_info = 18'h1ed75;
            6'd31: tbl_ver_info = 18'h1f250;
            6'd32: tbl_ver_info = 18'h209d5;
            6'd33: tbl_ver_info = 18'h216f0;
            6'd34: tbl_ver_info = 18'h228ba;
            6'd35: tbl_ver_info = 18'h2379f;
            6'd36: tbl_ver_info = 18'h24b0b;
            6'd37: tbl_ver_info = 18'h2542e;
            6'd38: tbl_ver_info = 18'h26a64;
            6'd39: tbl_ver_info = 18'h27541;
            6'd40: tbl_ver_info = 18'h28c69;
            default: tbl_ver_info = 18'h0;
        endcase
    end
endfunction

`endif  // QR_TABLES_VH
