#!/usr/bin/env python3
"""
Generate the Verilog include files that carry the QR version tables:

  rtl/qr_tables.vh      - block layouts, alignment centres, remainder bits,
                          char-count widths, version-information BCH codes
  rtl/qr_rs_gen_rom.vh  - Reed-Solomon generator-polynomial coefficients for
                          every distinct parity count used by versions 1-40

Tables are derived from scripts/golden_model.py and the `qrcode` reference
library. Re-run after changing the table sources:

    python scripts/gen_tables.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import golden_model as gm   # noqa: E402

RTL = os.path.join(os.path.dirname(HERE), "rtl")

VERSIONS = range(1, 41)


def blocks_flat(v, ec):
    """(n1, d1, n2, d2, ecc) for (v, ec); n2 = 0 when there is one size."""
    groups = gm.BLOCKS[v][ec]
    assert len(groups) <= 2, f"V{v} has {len(groups)} block-size groups"
    if len(groups) == 1:
        d, e, n = groups[0]
        return n, d, 0, 0, e
    (d1, e, n1), (d2, e2, n2) = groups
    assert e == e2, f"V{v}: mixed ECC per block"
    return n1, d1, n2, d2, e


def gen_qr_tables():
    L = []
    L.append("// GENERATED by scripts/gen_tables.py - DO NOT EDIT BY HAND.")
    L.append("// Derived from scripts/golden_model.py (qrcode reference library).")
    L.append("// Included INSIDE modules - no timescale directive allowed here.")
    L.append("// ISO 18004 tables for versions 1-40, all EC levels.")
    L.append("`ifndef QR_TABLES_VH")
    L.append("`define QR_TABLES_VH")
    L.append("")
    L.append("// total data codewords (payload capacity) per (version, ec)")
    L.append("function [11:0] tbl_data_cw;")
    L.append("    input [5:0] v;")
    L.append("    input [1:0] ec;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        row = " ".join(f"(ec == 2'd{ec}) ? 12'd{gm.DATA_CW[v][ec]} :"
                       for ec in (gm.EC_L, gm.EC_M, gm.EC_Q, gm.EC_H))
        L.append(f"            6'd{v}: tbl_data_cw = {row} 12'd0;")
    L.append("            default: tbl_data_cw = 12'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// total codewords (data + ecc) per (version, ec)")
    L.append("function [11:0] tbl_total_cw;")
    L.append("    input [5:0] v;")
    L.append("    input [1:0] ec;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        row = " ".join(f"(ec == 2'd{ec}) ? 12'd{gm.TOTAL_CW[v][ec]} :"
                       for ec in (gm.EC_L, gm.EC_M, gm.EC_Q, gm.EC_H))
        L.append(f"            6'd{v}: tbl_total_cw = {row} 12'd0;")
    L.append("            default: tbl_total_cw = 12'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// block layout per (version, ec):")
    L.append("//   {d1[6:0], n1[6:0], d2[6:0], n2[6:0], ecc[4:0]}")
    L.append("// n1 blocks carry d1 data codewords, n2 blocks carry d2 (d2 = d1+1")
    L.append("// whenever n2 > 0); ecc is uniform across all blocks of a version.")
    L.append("function [32:0] tbl_blocks;")
    L.append("    input [5:0] v;")
    L.append("    input [1:0] ec;")
    L.append("    reg [32:0] r;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        per_ec = []
        for ec in (gm.EC_L, gm.EC_M, gm.EC_Q, gm.EC_H):
            n1, d1, n2, d2, e = blocks_flat(v, ec)
            val = (d1 << 26) | (n1 << 19) | (d2 << 12) | (n2 << 5) | e
            per_ec.append(f"(ec == 2'd{ec}) ? 33'h{val:08x}")
        L.append(f"            6'd{v}: r = {' : '.join(per_ec)} : 33'h0;")
    L.append("            default: r = 33'h0;")
    L.append("        endcase")
    L.append("        tbl_blocks = r;")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// alignment-pattern centres: tbl_align_pos(v, i) for i < tbl_nalign(v)")
    L.append("function [2:0] tbl_nalign;")
    L.append("    input [5:0] v;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        n = len(gm.ALIGN_POS[v])
        L.append(f"            6'd{v}: tbl_nalign = 3'd{n};")
    L.append("            default: tbl_nalign = 3'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("function [7:0] tbl_align_pos;")
    L.append("    input [5:0] v;")
    L.append("    input [2:0] i;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        pos = gm.ALIGN_POS[v]
        if not pos:
            continue
        row = " ".join(f"3'd{i}: tbl_align_pos = 8'd{c};" for i, c in enumerate(pos))
        L.append(f"            6'd{v}: case (i) {row} default: tbl_align_pos = 8'd0; endcase")
    L.append("            default: tbl_align_pos = 8'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// remainder bits after the last data codeword")
    L.append("function [2:0] tbl_remainder;")
    L.append("    input [5:0] v;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        L.append(f"            6'd{v}: tbl_remainder = 3'd{gm.REMAINDER_BITS[v]};")
    L.append("            default: tbl_remainder = 3'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// char-count field width per (version, mode);")
    L.append("// mode: 0 = byte, 1 = numeric, 2 = alphanumeric, 3 = kanji")
    L.append("function [4:0] tbl_cnt_bits;")
    L.append("    input [5:0] v;")
    L.append("    input [1:0] mode;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        cb = gm.COUNT_BITS[v]
        row = ("(mode == 2'd1) ? 5'd{:d} : ".format(cb["numeric"]) +
               "(mode == 2'd2) ? 5'd{:d} : ".format(cb["alphanumeric"]) +
               "(mode == 2'd3) ? 5'd{:d} : ".format(cb["kanji"]) +
               "5'd{:d}".format(cb["byte"]))
        L.append(f"            6'd{v}: tbl_cnt_bits = {row};")
    L.append("            default: tbl_cnt_bits = 5'd8;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("// 18-bit version information (6 data + 12 BCH, G18 = 0x1F25);")
    L.append("// only defined for versions >= 7")
    L.append("function [17:0] tbl_ver_info;")
    L.append("    input [5:0] v;")
    L.append("    begin")
    L.append("        case (v)")
    for v in VERSIONS:
        if v < 7:
            continue
        L.append(f"            6'd{v}: tbl_ver_info = 18'h{gm.bch_version(v):05x};")
    L.append("            default: tbl_ver_info = 18'h0;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    L.append("`endif  // QR_TABLES_VH")
    path = os.path.join(RTL, "qr_tables.vh")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {path}")


def gen_rs_rom():
    parities = sorted({e for v in VERSIONS for ec in gm.EC_NAME
                       for d, e, n in gm.BLOCKS[v][ec]})
    L = []
    L.append("// GENERATED by scripts/gen_tables.py - DO NOT EDIT BY HAND.")
    L.append("// Reed-Solomon generator polynomial coefficients (GF(256), 0x11D),")
    L.append("// highest degree first, for every distinct parity count in V1-40:")
    L.append(f"//   {parities}")
    L.append("// gen_coeff(parity, i) = coefficient of x^(parity-1-i) of g_p(x).")
    L.append("`ifndef QR_RS_GEN_ROM_VH")
    L.append("`define QR_RS_GEN_ROM_VH")
    L.append("")
    L.append("function [7:0] gen_coeff;")
    L.append("    input [4:0] parity;")
    L.append("    input [4:0] idx;")
    L.append("    begin")
    L.append("        case (parity)")
    for p in parities:
        coeffs = gm.rs_generator(p)
        hexes = ", ".join(f"8'h{c:02x}" for c in coeffs)
        L.append(f"            5'd{p}: gen_coeff = rom{p}(idx);")
    L.append("            default: gen_coeff = 8'h00;")
    L.append("        endcase")
    L.append("    end")
    L.append("endfunction")
    L.append("")
    for p in parities:
        coeffs = gm.rs_generator(p)          # highest degree first, monic
        entries = [coeffs[p - k] for k in range(p)]
        L.append("function [7:0] rom%d;" % p)
        L.append("    input [4:0] idx;")
        L.append("    begin")
        L.append("        case (idx)")
        for k, c in enumerate(entries):
            L.append(f"            5'd{k}: rom{p} = 8'h{c:02x};")
        L.append(f"            default: rom{p} = 8'h00;")
        L.append("        endcase")
        L.append("    end")
        L.append("endfunction")
        L.append("")
    L.append("`endif  // QR_RS_GEN_ROM_VH")
    path = os.path.join(RTL, "qr_rs_gen_rom.vh")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {path} (parity counts: {parities})")


def print_capacity_summary():
    max_blocks = max(n1 + n2 for v in VERSIONS for ec in gm.EC_NAME
                     for n1, d1, n2, d2, e in [blocks_flat(v, ec)])
    max_d = max(max(d1, d2) for v in VERSIONS for ec in gm.EC_NAME
                for n1, d1, n2, d2, e in [blocks_flat(v, ec)])
    max_e = max(e for v in VERSIONS for ec in gm.EC_NAME
                for n1, d1, n2, d2, e in [blocks_flat(v, ec)])
    max_total = max(gm.TOTAL_CW[v][ec] for v in VERSIONS for ec in gm.EC_NAME)
    max_data = max(gm.DATA_CW[v][ec] for v in VERSIONS for ec in gm.EC_NAME)
    print(f"capacity summary: max blocks={max_blocks} max data/block={max_d} "
          f"max ecc/block={max_e} max total cw={max_total} "
          f"max data cw={max_data} max payload bytes={max_data}")


if __name__ == "__main__":
    gen_qr_tables()
    gen_rs_rom()
    print_capacity_summary()
